# Generated by Django 5.2.9 on 2025-12-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AddField(
            model_name='user',
            name='daily_reports_count',
            field=models.PositiveIntegerField(default=0, help_text='当天已生成的报告数量', verbose_name='今日报告数'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_report_date',
            field=models.DateField(blank=True, help_text='最后生成报告的日期', null=True, verbose_name='最后报告日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_expires_at',
            field=models.DateTimeField(blank=True, help_text='会员有效期截止日期', null=True, verbose_name='会员到期时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_level',
            field=models.CharField(choices=[('trial', '试用会员'), ('monthly', '月度会员'), ('quarterly', '季度会员'), ('yearly', '年度会员')], default='trial', help_text='用户的会员等级', max_length=20, verbose_name='会员等级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_calls_count',
            field=models.PositiveIntegerField(default=0, help_text='用户的API调用次数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, help_text='用户公司或组织名称', max_length=255),
        ),
    ]
