# Generated by Django 5.2.9 on 2025-12-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_daily_reports_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('organization', models.CharField(max_length=200, verbose_name='公司/机构')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('use_case', models.CharField(choices=[('market_analysis', '市场宏观分析'), ('competitor_tracking', '竞争对手追踪'), ('risk_monitoring', '舆情风险监测'), ('investment_research', '投资决策研报'), ('other', '其他定制需求')], default='market_analysis', max_length=50, verbose_name='主要用途')),
                ('message', models.TextField(blank=True, verbose_name='留言')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('contacted', '已联系'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='处理状态')),
                ('admin_notes', models.TextField(blank=True, verbose_name='管理员备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '试用申请',
                'verbose_name_plural': '试用申请管理',
                'db_table': 'trial_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
