# Generated by Django 5.2.9 on 2025-12-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_trialapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daily_reports_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_report_date',
        ),
        migrations.AddField(
            model_name='user',
            name='last_report_month',
            field=models.DateField(blank=True, help_text='最后生成报告的月份', null=True, verbose_name='最后报告月份'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_reports_count',
            field=models.PositiveIntegerField(default=0, help_text='当月已生成的报告数量', verbose_name='本月报告数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_level',
            field=models.CharField(choices=[('trial', '试用会员'), ('starter', '入门版'), ('pro', '专业版'), ('enterprise', '企业版')], default='trial', help_text='用户的会员等级', max_length=20, verbose_name='会员等级'),
        ),
    ]
