"""
User authentication views for the Django frontend.

Handles user registration, login, and logout functionality.
Also includes report viewing and export functionality.
"""
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse

from apps.reports.models import Report


def home(request):
    """Landing page view."""
    return render(request, 'index.html')


def login_view(request):
    """Handle user login."""
    if request.user.is_authenticated:
        # Redirect to Chainlit if already logged in
        return redirect('http://localhost:8001')
    
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'Welcome back, {username}!')
                # Redirect to Chainlit app
                return redirect('http://localhost:8001')
        else:
            messages.error(request, 'Invalid username or password.')
    else:
        form = AuthenticationForm()
    
    return render(request, 'login.html', {'form': form})


def register_view(request):
    """Handle user registration."""
    if request.user.is_authenticated:
        return redirect('http://localhost:8001')
    
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Account created successfully!')
            # Redirect to Chainlit app
            return redirect('http://localhost:8001')
    else:
        form = UserCreationForm()
    
    return render(request, 'register.html', {'form': form})


def logout_view(request):
    """Handle user logout."""
    logout(request)
    messages.info(request, 'You have been logged out.')
    return redirect('home')


@login_required
def reports_list(request):
    """Display list of user's reports."""
    reports = Report.objects.filter(
        user=request.user,
        status=Report.Status.COMPLETED
    ).order_by('-created_at')
    
    return render(request, 'reports/list.html', {'reports': reports})


@login_required
def report_detail(request, report_id):
    """Display a single report's details."""
    report = get_object_or_404(Report, id=report_id, user=request.user)
    return render(request, 'reports/detail.html', {'report': report})


@login_required
def report_export_markdown(request, report_id):
    """Export report as Markdown file."""
    report = get_object_or_404(Report, id=report_id, user=request.user)
    
    # Build Markdown content
    markdown_content = f"""# {report.query}

**Report ID:** {report.id}
**Created:** {report.created_at.strftime('%Y-%m-%d %H:%M')}
**Status:** {report.get_status_display()}

---

{report.output or 'No content available.'}

---

*Generated by AI Business Analysis Platform*
"""
    
    # Create response with file download
    response = HttpResponse(markdown_content, content_type='text/markdown')
    filename = f"report_{report.id}_{report.created_at.strftime('%Y%m%d')}.md"
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    
    return response

