# Generated by Django 5.2.9 on 2025-12-09 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='The keyword or topic for analysis', max_length=500)),
                ('output', models.TextField(blank=True, help_text='The final markdown report output')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of report generation', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if report generation failed')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the report was initiated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the report generation finished', null=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
