# Generated by Django 5.2.9 on 2025-12-09 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_chatsession_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, help_text='搜索关键词', max_length=500)),
                ('results_count', models.IntegerField(default=0, help_text='搜索结果数量')),
                ('results_json', models.JSONField(default=list, help_text='原始搜索结果 JSON')),
                ('formatted_results', models.TextField(blank=True, help_text='格式化的搜索结果文本')),
                ('search_source', models.CharField(default='bocha', help_text='搜索来源 (bocha, duckduckgo, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='搜索时间')),
                ('report', models.ForeignKey(blank=True, help_text='关联的报告', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_results', to='reports.report')),
            ],
            options={
                'verbose_name': '搜索结果',
                'verbose_name_plural': '搜索结果',
                'db_table': 'search_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
