# Generated by Django 5.2.9 on 2025-12-09 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_searchresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, help_text='爬取的 URL 地址', max_length=2000)),
                ('raw_content', models.TextField(blank=True, help_text='原始爬取内容 (Markdown)')),
                ('summary', models.TextField(blank=True, help_text='LLM 总结后的内容')),
                ('content_length', models.IntegerField(default=0, help_text='原始内容长度')),
                ('crawl_method', models.CharField(choices=[('jina', 'Jina AI Reader'), ('firecrawl', 'Firecrawl'), ('beautifulsoup', 'BeautifulSoup'), ('other', 'Other')], default='jina', help_text='爬取方式', max_length=20)),
                ('success', models.BooleanField(default=True, help_text='爬取是否成功')),
                ('error_message', models.TextField(blank=True, help_text='错误信息（如果失败）')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='爬取时间')),
                ('report', models.ForeignKey(blank=True, help_text='关联的报告', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawled_contents', to='reports.report')),
            ],
            options={
                'verbose_name': '爬取内容',
                'verbose_name_plural': '爬取内容',
                'db_table': 'crawled_contents',
                'ordering': ['-created_at'],
            },
        ),
    ]
